apiVersion: v1
kind: Service
metadata:
  labels:
    contrib.eventing.knative.dev/release: devel
    control-plane: dockerhub-source-controller-manager
  name: dockerhub-source-controller-manager
  namespace: knative-sources
spec:
  selector:
    control-plane: dockerhub-source-controller-manager
  ports:
  - port: 443
