apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerhub-source-webhook
  namespace: knative-sources
  labels:
    contrib.eventing.knative.dev/release: devel
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: dockerhub-source-webhook
      role: dockerhub-source-webhook
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels: *labels
    spec:
      serviceAccountName: dockerhub-source-webhook
      containers:
        - name: dockerhub-source-webhook
          terminationMessagePolicy: FallbackToLogsOnError
          image: ko://github.com/tom24d/eventing-dockerhub/cmd/webhook
          env:
          - name: SYSTEM_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CONFIG_LOGGING_NAME
            value: config-logging
          - name: METRICS_DOMAIN
            value: knative.dev/eventing
          - name: WEBHOOK_NAME
            value: dockerhub-source-webhook
          ports:
          - containerPort: 9090
            name: metrics
          readinessProbe: &probe
            periodSeconds: 1
            httpGet:
              scheme: HTTPS
              port: 8443
              httpHeaders:
              - name: k-kubelet-probe
                value: "webhook"
          livenessProbe: *probe

---

apiVersion: v1
kind: Service
metadata:
  labels:
    contrib.eventing.knative.dev/release: devel
    role: dockerhub-source-webhook
  name: dockerhub-source-webhook
  namespace: knative-sources
spec:
  ports:
    - name: https-webhook
      port: 443
      targetPort: 8443
  selector:
    role: dockerhub-source-webhook
